!obj:pylearn2.train.Train {
    dataset: &train !obj:contest_dataset.ContestDataset {
                        which_set: 'train',
                        start: 0,
                        stop: 3000
                },
    model: !obj:pylearn2.models.mlp.MLP {
        layers:  [ !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: %(h_0)d,
                     sparse_init: 15,
                 }, !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 7,
                     irange: 0.
                 }
                ],
       nvis: 2304,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 100,
        learning_rate: %(learning_rate)e,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:contest_dataset.ContestDataset {
                              which_set: 'train',
                              start: 3001,
                              stop: 3500
                          },
                'test'  : !obj:contest_dataset.ContestDataset {
                              which_set: 'train',
                              start: 3501,
                              stop: 4170
                          }
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts { costs: [
            !obj:pylearn2.costs.cost.MethodCost {
                method: 'cost_from_X',
                supervised: 1
            }, !obj:pylearn2.models.mlp.WeightDecay {
                coeffs: [ %(wd1)e, %(wd2)e ]
            }
            ]
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 20
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "%(save_path)s_best.pkl"
        },
    ],
    save_path: "%(save_path)s.pkl",
    save_freq: 1
}
